# Generated by Django 5.1.7 on 2025-04-29 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('trail_pending', 'Trail Pending Approval'), ('trail_approved', 'Trail Approved'), ('trail_rejected', 'Trail Rejected'), ('message', 'New Message'), ('group_add', 'Added to Group'), ('premium', 'Premium Purchase'), ('sos', 'SOS Alert'), ('custom', 'Custom Message')], default='custom', max_length=20),
        ),
    ]
