# Generated by Django 5.1.7 on 2025-04-10 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
    ]
