# Generated by Django 5.1.7 on 2025-04-05 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard'), ('expert', 'Expert')], max_length=10)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('elevation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('related_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='trails.trail')),
            ],
        ),
        migrations.CreateModel(
            name='TrailPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trails.trailimage')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='trails.trail')),
            ],
        ),
        migrations.CreateModel(
            name='PointImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trails.trailpoint')),
            ],
        ),
    ]
