# Generated by Django 5.1.7 on 2025-04-27 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('images', models.JSONField(default=list)),
                ('checklist', models.JSONField(default=list)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(max_length=50)),
                ('distance_km', models.FloatField()),
                ('highest_altitude', models.IntegerField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfflineMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='offline_maps/')),
                ('map_type', models.CharField(default='GeoJSON', max_length=50)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_maps', to='trails.trail')),
            ],
        ),
        migrations.CreateModel(
            name='TrailReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trails.trail')),
                ('written_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrailSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routed', models.BooleanField(default=True)),
                ('points', models.JSONField(default=list)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='trails.trail')),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('images', models.JSONField(default=list)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='trails.trail')),
            ],
        ),
    ]
