# Generated by Django 5.1.7 on 2025-04-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trail_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaypointImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='waypoint_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trail',
            name='images',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='images',
        ),
        migrations.AddField(
            model_name='trail',
            name='images',
            field=models.ManyToManyField(related_name='trails', to='trails.trailimage'),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='images',
            field=models.ManyToManyField(related_name='waypoints', to='trails.waypointimage'),
        ),
    ]
