# Generated by Django 5.1.7 on 2025-04-10 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_user_userpreference_userprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='likes_group_rides',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='wants_event_notifications',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_emergencycontact_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='preferred_length',
            field=models.CharField(blank=True, choices=[('Short', 'Short (<5 km)'), ('Medium', 'Medium (5-15 km)'), ('Long', 'Long (>15 km)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='preferred_terrain',
            field=models.CharField(blank=True, choices=[('Gravel', 'Gravel'), ('Asphalt', 'Asphalt'), ('Snow', 'Snow'), ('Forest', 'Forest')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_difficulty',
            field=models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_trail_type',
            field=models.CharField(blank=True, choices=[('Mountain', 'Mountain'), ('Road', 'Road'), ('Coastal', 'Coastal'), ('Forest', 'Forest')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddConstraint(
            model_name='emergencycontact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user', 'is_primary'), name='unique_primary_contact'),
        ),
    ]
